### ISSUE TITLE
Ch06 replaceword.c reads the same line twice

### ISSUE THREAD

**Issue by urashimaeffect0083** [PacktPublishing/C-Programming-Cookbook#1]
Below while loop reads the same line of data twice. 
while (!feof(fp)) {
   ll = strlen(line);
....
} 

I got below error: 

I am trying to create a sequential file. it was through C programming. It was very hot today. I have a cat. do you like animals? It might rain. Thank you. bye
I am trying to create a sequential file. it was through C programming. It was very hot today. I have a cat. do you like animals? It might rain. Thank you. bye

*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

I replaced above code with below, solved the problem.
while (fgets(line,sizeof(line),fp) != NULL) {
....
}

**Comment by bmharwani** [comment]
you are right.If there is an Enter key after the last line in the file, the last line will be displayed twice. The sizeof will check for the empty line
Thanks
    On Monday, 24 August, 2020, 10:13:07 am GMT-7, urashimaeffect0083 <notifications@github.com> wrote:  
 
 


Below while loop reads the same line of data twice.
while (!feof(fp)) {
ll = strlen(line);
....
}

I got below error:

I am trying to create a sequential file. it was through C programming. It was very hot today. I have a cat. do you like animals? It might rain. Thank you. bye
I am trying to create a sequential file. it was through C programming. It was very hot today. I have a cat. do you like animals? It might rain. Thank you. bye

*** stack smashing detected ***: terminated
Aborted (core dumped)

I replaced above code with below, solved the problem.
while (fgets(line,sizeof(line),fp) != NULL) {
....
}

**Comment by ManikandanKurup-Packt** [comment]
Hi @urashimaeffect0083 
can we close this issue if your query has been resolved?

**Comment by ManikandanKurup-Packt** [comment]
Please reopen if the issue still persists
